### ISSUE TITLE
Proposer une organisation de l'archivage des comptes

### ISSUE THREAD

**Issue by aangelot** [ccnum/spip4_mutualise#29]
Actuellement pas d'archivage des comptes sur les anciennes CCN 
=> nécessité de purger certaines informations (enjeux de sécurité en particulier)

**Comment by aangelot** [comment]
- Pour les CCN archivées : solution de Yassin 
- Pour les CCN en cours : suppression des comptes associés aux années passées (attention toutefois aux comptes qui servent encore sur l'année actuelle)

**Comment by pierretux** [comment]
ba on purgent en aout donc on peut tout delete et refaire les comptes ?

**Comment by ChristoErasme** [comment]
oui on peut tout à fait purger et refaire les comptes à la rentrée en septembre avec les nouveaux inscrits, je ne suis pas compétent mais ça me semble simple à condition que les personnes qui travaillent sur la CCN plusieurs années de suite conservent les mêmes droits et les mêmes accès : les intervenants, les admin, certains profs. Si courant aout tout ce petit monde n'a plus accès et que la CCN est en maintenance c'est acceptable. (Un point à vérifier : qu'une CCN archivée, purgée de ses comptes rédacteurs et admin, n'autorise pas tout de même les commentaires sur les articles ?)

**Comment by pierretux** [comment]
qu'une CCN archivée, purgée de ses comptes rédacteurs et admin, n'autorise pas tout de même les commentaires sur les articles ? => ça se ferme un forum via la config

**Comment by ChristoErasme** [comment]
on est d'accord, y'a un travail de maintenance à ce niveau qui n'est surement pas à jour... on en reparle pour vérifier qui fait quoi

**Comment by aangelot** [comment]
1. CCN en cours => stérilisation 
2. CCN arrêtée => passage sous format WACZ, attention aux clics non enregistrés : comportements bizarres. Question des vidéos : besoin de regarder toute la vidéo. Pas besoin d'enregistrer toutes les années, parfois une seule année de démo suffit ! Bien penser à modifier les URL des articles qui parlent de ces CCN : le lien d'archive sera différent 
3. CCN perdue => retrouver les rendus, et voir si c'est possible de les reporter dans SPIP 4 pour archivage

**Comment by aangelot** [comment]
@cmonnet faire ci dessous la liste des CCN avec les CCN à garder sous SPIP 4 (en cours ou en pause), les CCN à archiver sous WACZ, les CCN à récupérer sur le serveur et cassées
