### ISSUE TITLE
MAJ de rentrée CCN Fictions

### ISSUE THREAD

**Issue by ChristoErasme** [ccnum/spip4_mutualise#30]
A faire dès que possible sur la CCN Fictions :
- Afficher la bio de l'auteur : cette année encore il s'agit de Wilfried N'Sondé (idem an dernier)
- Afficher le prologue (texte ci-joint) visible
- Mettre en ligne le 1er chapitre (texte ci joint à la suite du prologue) et faire en sorte qu'on ne voit que le dernier paragraphe
- enlever le lien en bas "blog de l'auteur"
- vérifier que lorsqu'on se log sur Fictions on arrive bien sur l'année en cours 2024-2025 avec le bon auteur et le bon prologue (cf bug signalé sur l'arrivée sur l'année 2020-21 avec Pierre Ducrozet) qui doit être dû à une ligne de code pour forcer ce comportement... (supposition)
- relier l'espace doc à https://www.laclasse.com/portail/#app.doc/node/12077944 (à vérifier ultérieurement avec Thomas Neveu)

[sous l'oeil du vivant.docx](https://github.com/user-attachments/files/16759600/sous.l.oeil.du.vivant.docx)

**Comment by ChristoErasme** [comment]
Merci de faire cette maj dès que possible, elle doit servir à la com de rentrée vers les enseignants

**Comment by pierretux** [comment]
Pour : vérifier que lorsqu'on se log sur Fictions on arrive bien sur l'année en cours 2024-2025 avec le bon auteur et le bon prologue (cf bug signalé sur l'arrivée sur l'année 2020-21 avec Pierre Ducrozet) qui doit être dû à une ligne de code pour forcer ce comportement... (supposition) => cela rejoint le #6 il me semble ?

**Comment by ChristoErasme** [comment]
En effet, je le rappelais car #6 et #30 sont liés. Je voudrais qu'on puisse diffuser l'adresse du site pour relancer les inscriptions, et que l'on tombe bien sur la page de l'année avec le bon prologue et la fin du chapitre 1. Pour les classes et le reste du paramétrage du site on peut attendre.

**Comment by pierretux** [comment]
Ok mais ça demande de mettre à jour le texte directement en ligne je pense.
@ChristoErasme comment avec accès a un compte webmaster sur le site ?

**Comment by ChristoErasme** [comment]
Pierre, tu as un compte sur Fictions ? je ne trouve pas

**Comment by pierretux** [comment]
Un compte sur le cso logique avec mon mail

**Comment by ChristoErasme** [comment]
ok j'ai vu merci

**Comment by pierretux** [comment]
On serait ok la ?

**Comment by ChristoErasme** [comment]
hello, concernant https://fictions.laclasse.com/spip.php?page=sommaire on affiche actuellement la page des nouvelles (celle qu'on active en fin d'année pour lire les nouvelles) je crois, hors il faut afficher la page "écriture", avec le prologue puis le 1er chapitre à lire, et les carrés qui concernant les classes inscrites en dessous cf screenshot.

![Image](https://github.com/user-attachments/assets/9778572a-2a18-4b6f-b197-5966e051fbee)

**Comment by ChristoErasme** [comment]
oui mais c'est le Petit Fablab d'Ecriture, dans la version collège il doit y avoir aussi cet affichage

**Comment by pierretux** [comment]
Affichage corrigé mais à automatiser il me semble

**Comment by ChristoErasme** [comment]
je vois tjs le petit fablab affiché sur fictions... on devrait avoir la page d'accueil avec le prologue et le chapitre 1 de Wilfried N'Sondé... cc @Hunerva

**Comment by pierretux** [comment]
Ici https://fictions.laclasse.com/ ? Meme en navigation privé ?

**Comment by ChristoErasme** [comment]
en navigation privée ça fonctionne mais j'arrive tjs sur l'année de P Ducrozet.
après qd j'affiche 2024 ça marche, le prologue est bon
par contre le 1er chapitre doit être celui d'il y a 2 ans ? et les contenus de la fiche script aussi (je vais regarder de plus près après ma réunion.

**Comment by pierretux** [comment]
le soucis c'est que le site est encore en SPIP 3.2 donc avec les bogue de l'époque, il faut corrigé cela en dev pour la suite

**Comment by aangelot** [comment]
@pierretux on fait appel à @pvincent4 lundi matin qui a historiquement développé le projet. 
On te laisse préparer tes questions les plus chaudes sur la structure !

**Comment by ChristoErasme** [comment]
@pierretux en principe le chapitre 1 est à la suite du prologue dans le doc joint, et il n'y a pas encore de contenu pour la fiche script. De mon côté je mettrai à jour les années

**Comment by pierretux** [comment]
Ok mieux ?

**Comment by ChristoErasme** [comment]
ok, mais changer le titre : 
1/ Aux portes du désert marocain.
en
1/ Dans la maison au bord de la Bourges

**Comment by pierretux** [comment]
ok fait
On a un titre d'histoire ?

**Comment by ChristoErasme** [comment]
c'est bon, non y'a pas de titre au prologue
par contre si je viens (connecté) depuis laclasse.com, je devrais me retrouver connecté sur la CCN

**Comment by pierretux** [comment]
ça je ne peux pas tester, je n'ai pas de compte commun entre les 2
par contre ça marchait avant ou pas ? car on a rien toucher sur les serveurs de prod

**Comment by ChristoErasme** [comment]
oui ça fonctionnait avant, le principe c'est qu'on se connecte à l'ENT, et que lorsqu'on clique sur la tuile qui redirige vers la CCN on reste connecté. je mets @Hunerva en copie

**Comment by pierretux** [comment]
Je viens de test et mon compte passe très bien

**Comment by ChristoErasme** [comment]
ok j'ai testé sur un autre navigateur et ça fonctionne, peut être enlever 1 classe pour que cela s'affiche sur 1 ligne ?
merci !

**Comment by aangelot** [comment]
Bien être vigilant sur cette issue : le PFE n'a pas l'air de fonctionner sous SPIP4 (affichage des contenus en front). 
A noter pour le redéployement dans le dernière version à partir de lundi

**Comment by ChristoErasme** [comment]
le souci c'est que je n'arrive plus à me connecter , j'ai une erreur 403 qd je passe par se connecter
pour le souci remonté sur le petit fablab, mais qu'on risque de retrouver sur Fiction, c'est que sous Spip4 
(attention la petit fablab a été créé par @pvincent4 à partir de Air qui est devenu Fictions, mais il fonctionne de manière un peu différente)
Donc le souci était que la page de l'évènement était ok et en attente de participants : via le bouton JOUER (screen1)![Image](https://github.com/user-attachments/assets/502c394c-8c2e-43f1-8858-c251f75f6e0e)
![Image](https://github.com/user-attachments/assets/b8eeac52-1f96-4d3a-8ef6-e97098a508cd)

et que cela n'appelait pas la page d'écriture (screen2) qui est censée afficher le prologue à droite, et garder la collone de gauche qui décrit l'événement.

**Comment by pierretux** [comment]
Ah oui donc ce n'est pas fictions.
IL va resservir quand le site la prochaine fois ?

**Comment by ChristoErasme** [comment]
On ne sais pas encore, c'est au bon vouloir des médiathèques et festivals, mais à priori pas plus d'une à deux fois par an, et pour le moment je n'ai pas de demande datée. 
On pourra s'en occuper qd tu auras un moment en 2025 je pense

**Comment by pierretux** [comment]
Sauf que tu as le bogue en SPIP3 je pense non ? Si c'est le cas on a rien touché en code donc je pense que le soucis existe depuis un moment.

**Comment by ChristoErasme** [comment]
je ne pense pas, cela fonctionnait jusqu'ici, le 1er chapitre de l'an dernier était bien caché et seulement visible sur le dernier paragraphe, en tout cas pour mercredi ce sera important de ne pas afficher tout le chapitre ;)

**Comment by pierretux** [comment]
Non, si on joue avec la config du site on voit que le dernier chapitre est complet mais le précédent on affiche le dernier couplet en effet

**Comment by pierretux** [comment]
Oui ba c'est ce que prévoit le code, je ne l'ai pas toucher, j'ai pas accès au serveur

**Comment by ChristoErasme** [comment]
@pierretux dis nous lorsque le site Fiction est opérationnel, pour le moment 
je n'y accède qu'en navigation privée (mais ce doit être mon cache ?)
je vois tjs le 1er chapitre en entier même une fois connecté
je ne vois pas les comptes des classes, mais peut être que @Hunerva ne les a pas encore créé ?
merci de nous tenir au courant

**Comment by pierretux** [comment]
@ChristoErasme cela fonctionne comme les autres année, tu vu avec @Pipazoul  les tests que j'ai fait avec lui ?

**Comment by ChristoErasme** [comment]
non mais j'imagine que @Hunerva est en train de créer les classes et les contenus pour demain

**Comment by Hunerva** [comment]
Les rubriques sont créées et j'ai envoyé le fichier d'import utilisateur à Pierre. Je n'ai rien fait d'autre sur le site.

**Comment by pierretux** [comment]
Les imporrts sont fait en spip4 dc il faut remettre en spip 4 le site

Pierre KUHN

06 26 84 56 09

151 rue des capucines

42155 LENTIGNY

MAIL: ***@***.***

 Le mardi 1 octobre 2024 à 16:30, Thomas N.

**Comment by ChristoErasme** [comment]
Dsl si nos messages se croisent :  je vois tjs le 1er chapitre en entier même une fois connecté est il devrait être 10 fois le même : 
je ne vois pas les comptes des classes : à priori on devrait avoir les 9 cases du haut identiques avec le 1er chapitre par Wilfried N'Sondé, puis en dessous la répartition des 9 classes inscrites + celle de Wilfried N'Sondé (donc 10 carrés en tout) en mode écriture du chapitre 2 ? mais je ne sais pas qui fait ça habituellement ? ce n'est pas toi qui t'en est occupé l'an dernier ?

**Comment by Hunerva** [comment]
Pierre-Alexandre s'est toujours occupé de Fictions, je ne faisais que fournir le fichier d'import utilisateur avec les rubriques associées

**Comment by ChristoErasme** [comment]
Dans la version actuelle de Fictions, que @Pipazoul a re-migrée sous Spip 4, tout semble ok
reste à importer les utilisateurs (9 profs + 1 écrivain) 
@pierretux l'import des utilisateurs créé-t-il les rubriques ?
@Hunerva  si ça ne créé pas les rubriques peux-tu demain attribuer un article à chaque auteur ?
je suis en rv demain matin, je peux regarder sinon en fin de matinée ce que je peux faire.... sans l'avoir jamais fait non plus 

on va y arriver !

**Comment by pierretux** [comment]
Non, je ne créer pas les rubrique mais je rattache l'auteur aux rubriques indiquer dans le fichier.
J'ai fais les imports de compte à l'instant.

**Comment by ChristoErasme** [comment]
OK merci @pierretux pour ton aide
Je remets ici ce qu'on a fait au cas où et pour info @Hunerva (j'espère qu'on a pas fait de bêtises)
- les chapitres 1 sont publiés sur les 10 colonnes histoires et rendus masqués suite publication du chapitre 2
- les chapitres 2 sont publiés pour être prêts à être complétés par les classes
- les autres chapitres sont créés et associés aux auteurs, il faudra les publier durant l'année
- Pierre s'est retiré des auteurs ainsi que PAR afin de ne pas apparaitre
- J'ai modifié le nom des autres auteurs (profs) en les remplaçant par le nom de leur collèges pour plus de lisibilité
what else ?
