### ISSUE TITLE
MAJ de rentrée CCN OnTourne

### ISSUE THREAD

**Issue by ChristoErasme** [ccnum/spip4_mutualise#32]

**Comment by ChristoErasme** [comment]
Bizarrement je peux pas mettre de description au dessus. 
Remarque concernant https://ccn-dev.projets.erasme.org/ la CCN OnTourne et le mail d'@anthony , que faut-il vérifier ? en terme de MAJ ?

**Comment by pierretux** [comment]
Que le site est complet et que les fonctions du site sont OK : la connexion, la navigation, ....

**Comment by ChristoErasme** [comment]
Ce site n’est pas encore configuré. Revenez plus tard...

**Comment by pierretux** [comment]
Corrigé

**Comment by pierretux** [comment]
@ChristoErasme et @Hunerva  on peut tester la version https://ccn-dev.thematiques.laclasse.com/ complétement ?

**Comment by ChristoErasme** [comment]
ok merci @pierretux vu rapidement avt de partir en rv... (je refais une passe demain matin)
- je peux me connecter (ok)
- une fois connecté je peux choisir où publier mais cela n'est pas suivi d'effet
- vérifier mes statuts mais en tant qu'admin je devrais pouvoir publier partout, hors je n'ai pas le crayon
- les comportements des clics sur les logos CCN et Erasme sont différents, le premier ouvre la page et le second le fait dans une nouvelle fenêtre
- voir avec @Hunerva comment on mettra à jour les contenus ? nettoyer les messages des forums de l'an dernier, etc
- voir avec @JulMonaco les maj design au fur et à mesure (on est d'accord que ce sera effectif lors de la mise en prod sous Spip4 (actus, boutons, etc) ?

**Comment by ChristoErasme** [comment]
/!\ actuellement lorsque je choisi de publier dans n'importe quelle rubrique cela m'ouvre la fenêtre "discuter avec" au lieu de me donner le crayon dans le bon article

**Comment by pierretux** [comment]
>     * les comportements des clics sur les logos CCN et Erasme sont différents, le premier ouvre la page et le second le fait dans une nouvelle fenêtre ==> c'est le cas déjà en prod mais je vais forcer les 2 dans une nouvelle fenêtre

**Comment by pierretux** [comment]
Pas mal de correction ce matin sur les retours, à voir si on est ok maintenant.

**Comment by ChristoErasme** [comment]
je tombe sur une erreur 403 laclasse lorsque je me connecte via laclasse...

**Comment by pierretux** [comment]
@ChristoErasme tu peux re tester ?

**Comment by ChristoErasme** [comment]
@pierretux J'ai testé le crayon sur https://ccn-dev.thematiques.laclasse.com/  ça ne fonctionne pas : je peux maintenant choisir la rubrique, cela ouvre la fenêtre d'écriture du titre de l'article que je peux renseigner puis lorsque je valide, au lieu de m'ouvrir le corps de l'article à compléter, cela ferme la fenêtre comme si l'action n'avait pas eu lieu

**Comment by aangelot** [comment]
@pierretux on a creusé, le crayon crée bien un article dans la back-office. Cependant comme l'affichage sur le front est cassé on ne peut pas poursuivre les étapes comme la complétion de l'article

**Comment by pierretux** [comment]
est ce que maintenant cela fonctionne ?

**Comment by ChristoErasme** [comment]
non, je suis bien connecté, je peux cliquer sur le crayon pour publier, cela crée un article mais il ne s'affiche pas sur le front : voir mon dernier test de consigne.
- qd je complète mon article via /ecrire je vois qu'il a bien le statut "publié en ligne" mais on ne le vois pas sur le front "voir en ligne"
- il faudra aussi créer une année 2024-25

**Comment by pierretux** [comment]
@ChristoErasme ok mai ça marche pour toi ici https://selfdata.laclasse.com/ ? encore un SPIP 3.2

**Comment by ChristoErasme** [comment]
Non, là je ne vois même pas le crayon
Si tu veux on se retrouve en visio et je te fais un partage d'écran, avant 17h45 car je serai en rv après
je suis sur https://meet.jit.si/CCNCoordination

**Comment by ChristoErasme** [comment]
Sur   https://selfdata.laclasse.com/  lorsque je me connecte la première fois je tombe sur 2024-25 et je ne peux pas publier
Par contre si je bascule sur l'année 2023/24 ça fonctionne : le crayon + l'article en front 
Et pas moyen de revenir ni d'afficher 2024/25 qd je suis sur 2023/24

**Comment by ChristoErasme** [comment]
@pierretux j'ai essayé de te créer un compte auteur sur de vielles CCN https://aqueduc.laclasse.com/ ou https://14-18.laclasse.com/ mais si j'arrive bien à me connecter, je ne peux pas ajouter un auteur. 
![Image](https://github.com/user-attachments/assets/51232c98-8fac-4215-8940-72074fdda5e9)

**Comment by pierretux** [comment]
@ChristoErasme  pour le screen il faut passer sur configuration > admin des plugins pour corrigé

**Comment by ChristoErasme** [comment]
Oui, je voulais pas le faire car y'a tjs un pluggin qui se met en erreur. 
Du coup, ce que je vois sur 14-18 c'est que le site fonctionne jusqu'à ce que je mette à jour les pluggins
Là il affiche une nouvelle année (automatiquement) 2024-25, qui affiche la page d'accueil vierge, permet de se connecter via Sicas, affiche le crayon mais ne va pas au delà de la fenêtre de renseignement du titre en front
Par contre l'article a bien été crée et on peut le modifier /ecrire
Sauf qu'il ne s'affiche jamais en Front malgré son statut "publié en ligne"
ma question : y'a un pluggin qui peut perturber le truc ?
Si tu veux on refait la manip en partage d'écran sur un autre Spip ?
Mais surtout on perd du temps, je n'ai pas la compétence technique, il faudrait le faire avec un Dev qui a déjà mis les mains dans les CCN et je ne vois que @pvincent4

**Comment by pierretux** [comment]
@ChristoErasme ça marche pour toi cette url https://ccn-dev.thematiques.laclasse.com/spip.php?page=article&id_article=52&mode=complet ?

**Comment by ChristoErasme** [comment]
pas mieux que ce matin, je me connecte j'ai le crayon, j'écris le titre, il est bien dans le back mais pas visible en front (test consigne) dsl

**Comment by pierretux** [comment]
Mais avec l'url que je te donne tu n'a pas ;
![image](https://github.com/user-attachments/assets/5cb96004-7da7-40ec-ba55-7ea83c8a435e)

**Comment by ChristoErasme** [comment]
si, mais cela n'affiche pas mes publications

**Comment by aangelot** [comment]
@pierretux j'ai eu @racine-p-a au téléphone qui a gentiment regardé avec moi le problème. 

Au vu des retours consoles, on n'a pas détecté d'erreur, et Pierre-Alexandre n'a pas de souvenir d'un tel type de bugs... 

Si mercredi tu n'as toujours pas pu débugguer, tu peux le joindre sur le temps du midi.

**Comment by pvincent4** [comment]
Hello @all
Avez vous été voir ici https://github.com/ccnum/plugin_thematique_laclasse/wiki/Utilisation-1%E2%80%AF:-Cr%C3%A9er-une-nouvelle-CCN#Pr%C3%A9parer-la-premi%C3%A8re-ann%C3%A9e et notamment le mot clef "annee_en_cours" ?
Bon courage

**Comment by pierretux** [comment]
merci @pvincent4 en effet la doc est un peu décentralisé

@ChristoErasme La ccn de dev est up ce soir avec plain de correction faites, à voir si ça bogue encore

**Comment by ChristoErasme** [comment]
Bonjour @pierretux : sur Dev non, je ne peux tjs pas publier et je n'affiche ni l'année 2024 ni les contenus des années précédentes, la consigne qui d'affiche date de 2018 et le site passe en erreur 404...
Sur OnTourne en prod c'est tjs pareil

Tu as pu voir toute la doc sur les mots clés que Pierre Alexandre avait faite cf le lien envoyé hier par @pvincent4 ?

**Comment by ChristoErasme** [comment]
Si tu veux qu'on fasse 10mn de test en visio je suis dispo ce matin uniquement

**Comment by ChristoErasme** [comment]
@pierretux aujourd'hui Thomas anime des formations, il n'est pas dispo pour te faire passer un jeu de comptes avant demain, il va falloir que tu trouves un autre moyen pour faire ton test. Tu n'as pas un autre jeu de comptes fictifs qu'il t'aurait envoyé auparavant ? Tiens-moi au courant si je peux faire qq chose, je suis dispo jusqu'à 14h, sinon après 18h30.

**Comment by pierretux** [comment]
@ChristoErasme un peu de retard mais @Pipazoul a corrigé le JS (faudrait le recoder plus simple)
Pour les imports de csv cela fonctionne en local, et j'ai passé en prod pour la suite.

**Comment by ChristoErasme** [comment]
c'est top merci, dès que @Hunerva peut importer les comptes fais moi signe je lui transmettrai
sinon j'ai testé https://ontourne.laclasse.com/ en prod ça fonctionne, il y a juste l'agenda et le blog pédago que je ne peux pas afficher à première vue

**Comment by ChristoErasme** [comment]
j'attends ton feu vert pour tester les autres

**Comment by pierretux** [comment]
On peut pas car les rubriques dans le BO existe pas ?

**Comment by ChristoErasme** [comment]
Top, merci @pierretux et @Pipazoul la CCN OnTourne fonctionne, j'ai pu publier la première consigne et je confirme que les classes vont pouvoir y répondre avec le bouton ad hoc \o/

En bas de page le bouton ressource qui doit afficher les docs sur laclasse.com n'apparait pas et semble mal nommé, "cartable ligne" au lien de "cartable en ligne". Je ne sais pas qui peut rétablir ça ? @Hunerva a bien lié les docs de l'ENT qui y correspondent

![Image](https://github.com/user-attachments/assets/feba9779-af6c-47b1-bc15-a10cb5ef40cb)

**Comment by Th0mas-N** [comment]
> Top, merci @pierretux et @Pipazoul la CCN OnTourne fonctionne, j'ai pu publier la première consigne et je confirme que les classes vont pouvoir y répondre avec le bouton ad hoc \o/
> 
> En bas de page le bouton ressource qui doit afficher les docs sur laclasse.com n'apparait pas et semble mal nommé, "cartable ligne" au lien de "cartable en ligne". Je ne sais pas qui peut rétablir ça ? @Hunerva a bien lié les docs de l'ENT qui y correspondent
> 
> ![Image](https://private-user-images.githubusercontent.com/179570254/372486528-feba9779-af6c-47b1-bc15-a10cb5ef40cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODk2NjIsIm5iZiI6MTcyNzc4OTM2MiwicGF0aCI6Ii8xNzk1NzAyNTQvMzcyNDg2NTI4LWZlYmE5Nzc5LWFmNmMtNDdiMS1iYzE1LWExMGNiNWVmNDBjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxMzI5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNDVhM2JjMDFhNDcwOWIwNjZmYTZmMzk2OGVkOGI0YTI4OTAzYmU2NWQwNWVjZmZlN2U0NTNkMjZhNTJhYmM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5LVBy-fzglQS4sFzxjQ_n1o6OxbMLR8RwbRD9pStdPQ)

Je me suis permis de déplacer ton article qui n'était pas dans la bonne rubrique

**Comment by ChristoErasme** [comment]
comment ça pas dans la bonne rubrique ?

**Comment by ChristoErasme** [comment]
@pierretux le pb du bouton "cartable en ligne" apparait également sur les la CCN Textile et les autres...

**Comment by ChristoErasme** [comment]
ah oui @Hunerva j'ai du le publier dans Tuba&Silvia au lieu de Consignes non ?

**Comment by pierretux** [comment]
@ChristoErasme  c'est ok dans 15 minutes pour "cartable ligne", le temps que les serveurs se relance

**Comment by Th0mas-N** [comment]
> ah oui @Hunerva j'ai du le publier dans Tuba&Silvia au lieu de Consignes non ?

Non c'est l'inverse, tu l'as publié dans "consignes" alors que ça devrait être dans "2024 > Consignes > Tuba & Silvia".
D'ailleurs, je ne sais pas ce que c'est que cette rubrique "consignes" à la racine et à quoi elle sert.

**Comment by ChristoErasme** [comment]
ah, je croyais pourtant l'avoir publié exactement là : "2024 > Consignes > Tuba & Silvia". j'ai dû me tromper

**Comment by ChristoErasme** [comment]
merci @pierretux je regarde dans 15mn et on peut passer à Fictions ?

**Comment by pierretux** [comment]
On est ok sur cette issue du coup ?

**Comment by pierretux** [comment]
> [@pierretux](https://github.com/pierretux) le pb du bouton "cartable en ligne" apparait également sur les la CCN Textile et les autres...

C'est ok maintenant
