### ISSUE TITLE
Page accueil ccn Fictions

### ISSUE THREAD

**Issue by cmonnet** [ccnum/spip4_mutualise#6]
La page https://fictions.laclasse.com/ point le plus souvent sur l'année 2021, voir dans le code s'il y a qq chose dans ce sens et le corriger pour qu'on pointe bien sur l'année en cours. Avec les nouvelles en front pour les années passées, et les carrés d'écriture pour l'année en cours entre octo et mai

**Comment by ChristoErasme** [comment]
cf ma réponse ici https://github.com/ccnum/ccn/issues/26
